In [503]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [504]:
x = pd.read_csv('new_train_data.csv').values
x_test=pd.read_csv('new_test_data.csv', error_bad_lines=False).values

In [505]:
X=x[:,:13]
Y=x[:,13]
X

array([[1.0000000e+00, 7.0000000e+00, 1.2442373e+07, ..., 1.0924403e+07,
        1.5900000e+02, 4.4089160e+06],
       [1.5000000e+01, 7.0000000e+00, 1.1007835e+07, ..., 9.4447220e+06,
        1.4800000e+02, 2.3791690e+06],
       [9.0000000e+00, 1.0000000e+01, 8.4366750e+06, ..., 7.8967280e+06,
        1.2300000e+02, 6.3650200e+05],
       ...,
       [4.0000000e+00, 5.0000000e+00, 3.6828000e+04, ..., 3.7528000e+04,
        2.7000000e+01, 1.0615300e+05],
       [1.6000000e+01, 6.0000000e+00, 3.6805000e+04, ..., 3.3125000e+04,
        1.5000000e+01, 2.4720000e+04],
       [2.0000000e+01, 6.0000000e+00, 3.6776000e+04, ..., 3.2694000e+04,
        3.0000000e+01, 3.1040600e+06]])

In [506]:
Y

array([163115.,  80188., 141000.,  55123.,  33204., 145606., 145606.,
        44957.,  23432., 218502.,  14001.,  37220.,  15764.,  22413.,
        44700.,  15764., 150793.,  12446.,  21374.,  24402.,  23610.,
         9439.,  10219.,  12847.,   3834.,  50341.,  12365.,  15003.,
         6092.,   6250.,  20018.,  20133.,  10287.,  11243.,   3201.,
         3702.,   5840.,  22861.,  24507.,  14726.,   7089.,   5683.,
        20839.,  21005.,  14249.,   7292.,  15118.,  19525.,  10280.,
        25127.,  10895.,   9971.,   8540.,   8139.,   3201.,   6031.,
         4066.,   9537.,   6480.,   8783.,  10586.,  13590.,   8911.,
         8440.,  34227.,   7067.,  10239.,  10071.,   5514.,  12294.,
         5054.,   7172.,   8842.,   9711.,   9179.,  12265.,   1996.,
        11254.,   9052.,   3317.,   6391.,   9572.,  10687.,  11045.,
        10652.,  30609.,   4967.,   4937.,   8843.,   3807.,   2095.,
         9634.,   9179.,   5440.,   9846.,   7697.,  10070.,  10418.,
         4205.,   87

In [507]:
std=np.std(X,axis=0)
u=np.mean(X,axis=0)
print(std)
print(u)

[9.13935941e+00 5.20990330e+00 8.59412715e+05 3.67589388e+01
 2.08757997e+00 6.88814488e+00 8.22041518e-01 3.00046685e+01
 2.59628027e+01 2.65840200e-01 7.56319032e+05 2.87897541e+01
 1.56498437e+06]
[1.68233799e+01 5.72299873e+00 3.10283391e+05 9.05716645e+02
 2.61791614e+01 3.09428208e+01 2.01524778e+00 9.60838628e+01
 1.50298602e+02 4.97069191e-01 2.91001114e+05 4.18526048e+01
 1.45794499e+06]


In [508]:
X=(X-u)/std
print(X)

[[-1.73134453  0.24511036 14.1167211  ... 14.05941334  4.06906551
   1.88562331]
 [-0.1995085   0.24511036 12.44751378 ... 12.10298895  3.68698513
   0.58864742]
 [-0.85600966  0.82093679  9.4557498  ... 10.05624157  2.81862064
  -0.52488895]
 ...
 [-1.40309395 -0.13877392 -0.31818867 ... -0.33514047 -0.51589898
  -0.86377348]
 [-0.09009164  0.05316822 -0.31821544 ... -0.34096209 -0.93271394
  -0.91580787]
 [ 0.34757579  0.05316822 -0.31824918 ... -0.34153195 -0.41169524
   1.05184118]]


In [509]:
ones=np.ones((X.shape[0],1))
X = np.hstack((ones,X))
print(X)

[[ 1.         -1.73134453  0.24511036 ... 14.05941334  4.06906551
   1.88562331]
 [ 1.         -0.1995085   0.24511036 ... 12.10298895  3.68698513
   0.58864742]
 [ 1.         -0.85600966  0.82093679 ... 10.05624157  2.81862064
  -0.52488895]
 ...
 [ 1.         -1.40309395 -0.13877392 ... -0.33514047 -0.51589898
  -0.86377348]
 [ 1.         -0.09009164  0.05316822 ... -0.34096209 -0.93271394
  -0.91580787]
 [ 1.          0.34757579  0.05316822 ... -0.34153195 -0.41169524
   1.05184118]]


In [510]:
twos=np.ones((x_test.shape[0],1))
x_test=np.hstack((twos,x_test))
print(x_test)

[[1.00000e+00 3.20000e+01 1.80000e+01 ... 3.42370e+04 1.70000e+01
  2.76900e+03]
 [1.00000e+00 9.00000e+00 1.90000e+01 ... 3.43280e+04 1.30000e+01
  6.36502e+05]
 [1.00000e+00 2.50000e+01 8.00000e+00 ... 3.24340e+04 1.70000e+01
  2.42367e+05]
 ...
 [1.00000e+00 1.10000e+01 1.20000e+01 ... 5.22000e+02 6.00000e+00
  1.05882e+05]
 [1.00000e+00 1.10000e+01 1.20000e+01 ... 9.40000e+01 8.00000e+00
  1.05882e+05]
 [1.00000e+00 2.00000e+01 4.00000e+00 ... 0.00000e+00 6.00000e+00
  3.10406e+06]]


In [511]:
df=pd.DataFrame(X)
print(df)

       0         1         2          3         4         5         6  \
0    1.0 -1.731345  0.245110  14.116721 -0.754011 -1.522893  0.153478   
1    1.0 -0.199509  0.245110  12.447514 -1.298096  0.393201 -0.136876   
2    1.0 -0.856010  0.820937   9.455750  0.823836  0.872225  0.879363   
3    1.0  1.222911  0.820937   7.562940  0.660611 -1.522893  0.008301   
4    1.0 -0.418342  0.820937   6.120810 -1.461322  1.351248 -0.862761   
..   ...       ...       ...        ...       ...       ...       ...   
782  1.0 -0.418342 -0.138774  -0.318042 -1.624548 -1.522893 -0.427230   
783  1.0  0.785243 -0.138774  -0.318050  1.068675 -1.522893  0.734186   
784  1.0 -1.403094 -0.138774  -0.318189  3.081791  0.872225 -0.427230   
785  1.0 -0.090092  0.053168  -0.318215 -0.155517 -1.043870 -3.621123   
786  1.0  0.347576  0.053168  -0.318249 -0.454764 -0.564846  0.879363   

            7         8         9        10         11        12        13  
0   -0.018549  4.096567 -0.011501  0.765010  1

In [512]:
df.head()

0         1         2          3         4         5         6         7  \
0  1.0 -1.731345  0.245110  14.116721 -0.754011 -1.522893  0.153478 -0.018549   
1  1.0 -0.199509  0.245110  12.447514 -1.298096  0.393201 -0.136876 -0.018549   
2  1.0 -0.856010  0.820937   9.455750  0.823836  0.872225  0.879363  1.197935   
3  1.0  1.222911  0.820937   7.562940  0.660611 -1.522893  0.008301 -0.018549   
4  1.0 -0.418342  0.820937   6.120810 -1.461322  1.351248 -0.862761 -1.235032   

          8         9        10         11        12        13  
0  4.096567 -0.011501  0.765010  14.059413  4.069066  1.885623  
1  3.963254  1.760264  1.590990  12.102989  3.686985  0.588647  
2  3.863270 -1.860300 -1.504603  10.056242  2.818621 -0.524889  
3  4.029911 -1.244034  1.243887   7.989050  2.367071 -0.851042  
4  4.363192 -1.590684  1.319861   5.890552  1.081892 -0.749510

In [513]:
def hypothesis(X,theta):
    return np.dot(X,theta)
def error(X,Y,theta):
    error=0.0
    m=X.shape[0]
    y_=hypothesis(X,theta)
    e=np.sum((Y-y_)**2)
    return e/m
def gradient(X,Y,theta):
    y_=hypothesis(X,theta)
    grad=np.dot(X.T,(y_ - Y))
    m=X.shape[0]
    return grad/m
def gradient_descent(X,Y,learning_rate=0.00001,max_epochs=1):
    n=X.shape[1]
    print(n)
    theta=np.zeros((n,))
    print(theta)
    error_list=[]
    print(error_list)
    for i in range(max_epochs):
        
        e=error(X,Y,theta)
        error_list.append(e)
        
        grad=gradient(X,Y,theta)
        theta=theta-learning_rate*grad
    return theta,error_list

In [514]:
theta,error_list=gradient_descent(X,Y)
print(theta)

14
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[]
[ 6.61564676e-02 -1.91116135e-02 -9.74393098e-05  1.10214084e-01
 -2.07681379e-03  9.93969677e-04  2.81071856e-03  2.23360355e-03
  5.95198204e-02  5.22174385e-03 -1.35535264e-03  1.10391701e-01
  5.34977094e-02  2.63803666e-02]


In [515]:
print(error_list)

[271731519.5908513]


In [516]:
y_test=hypothesis(x_test,theta)
print(y_test)

[  7910.21464161  24634.80266032  14025.65241735 123951.86285789
  89483.27339578  24647.536486   123913.95717351  11028.09046576
  24561.38540725  46315.89148291  47081.99497981 123796.59628074
   7642.48385212  11972.00682091 123760.91969737  24495.6345856
  24477.66731485  18721.02869227  18722.56448812  13665.37220096
  24388.02887305  46282.86983389   9012.45960699 123687.20739455
  46163.86098356  24340.85317379 131042.77556145  89110.85722917
   7525.33621041  14717.63835239  24189.55452613  46045.21101096
  50522.1195339  123508.40799705 123425.46565277  13562.46738965
  89014.55805241  46017.1777431   18435.85437756  45971.28183421
 130796.0709954  123447.73977038  18010.42518383  14557.73293048
   9783.10821016  18400.3511604   31538.34619035  31545.68753718
  18331.37318408 123355.34779827  11520.53817107  11547.47925513
  33190.58260475   9067.75380802  14383.94002281  13458.23506455
  88929.84916087  31505.78960652  10522.1476693  130681.10239407
  45785.79478951 123275.52

In [517]:
testdata = pd.read_csv('Test_dataset1.csv').values
city =testdata[:,0]
df=pd.DataFrame(data=city,columns=["City"])
# df=pd.DataFrame(data=y_test,columns=["Covid Cases"])
# df['City'] = city
df['Covid Cases'] = y_test 
df['Covid Cases'] = df['Covid Cases'].apply(np.int64)
print(df)

             City  Covid Cases
0        Tuensang         7910
1    Lakshmeshwar        24634
2            Zira        14025
3           Yawal       123951
4    Thana Bhawan        89483
..            ...          ...
496   Nandaprayag         3127
497    Kirtinagar         3103
498     Kedarnath         2918
499      Gangotri         2816
500     Kumarganj        84613

[501 rows x 2 columns]


In [518]:
df.to_csv("Part - 01 Solution Data.csv",index=True)